function loadJSFXR(data, resolve) {
  var buff = base64ToArrayBuffer(data.substr(22));
  kz.audio_context.decodeAudioData(buff, resolve);
}

function loadSonant(data, resolve) {
  var songGen = new sonantx.MusicGenerator(data);
  songGen.createAudioBuffer(resolve);
}

var resources = {
  images: {
    background: {x:36,y:263,w:32,h:32},
    character_boar: {x:0,y:0,w:0,h:0,W:0,H:0,f:1},
    character_cat: {x:37,y:0,w:50,h:50,W:42,H:38,f:1},
    character_dog: {x:0,y:0,w:0,h:0,W:0,H:0,f:1},
    character_dragon: {x:0,y:0,w:0,h:0,W:0,H:0,f:1},
    character_hare: {x:0,y:0,w:0,h:0,W:0,H:0,f:1},
    character_horse: {x:0,y:0,w:0,h:0,W:0,H:0,f:1},
    character_monkey: {x:0,y:0,w:0,h:0,W:0,H:0,f:1},
    character_ox: {x:0,y:0,w:0,h:0,W:0,H:0,f:1},
    character_rat: {x:0,y:0,w:0,h:0,W:0,H:0,f:1},
    character_rooster: {x:0,y:0,w:0,h:0,W:0,H:0,f:1},
    character_sheep: {x:0,y:0,w:0,h:0,W:0,H:0,f:1},
    character_snake: {x:0,y:0,w:0,h:0,W:0,H:0,f:1},
    character_tiger: {x:0,y:0,w:0,h:0,W:0,H:0,f:1},
    character_random: {x:0,y:0,w:0,h:0,W:0,H:0,f:1},
    piece_blue: {x:0,y:0,w:0,h:0},
    piece_red: {x:0,y:0,w:0,h:0},
    piece_zodiac: {x:0,y:0,w:0,h:0},
    shooter_0: {x:68,y:260,w:9,h:22,W:9,H:22,f:1},
    shooter_1: {x:0,y:0,w:0,h:0,W:0,H:0,f:1},
    shooter_2: {x:0,y:0,w:0,h:0,W:0,H:0,f:1},
    shooter_3: {x:68,y:260,w:9,h:22,W:9,H:22,f:1}
  },
  sounds: {
    'sfx_shoot': {
      data: jsfxr([0,,0.1881,,0.3164,0.8042,0.2,-0.2915,,,,,,0.4661,0.156,,0.1754,-0.182,1,,,0.1755,,0.5]),
      loader: loadJSFXR
    },
    'sfx_clear': {
      data: jsfxr([1,,0.06,0.4848,0.4938,0.8917,,,,,,,,,,,,,1,,,,,0.49]),
      loader: loadJSFXR
    },
    'sfx_select': {
      data: jsfxr([0,,0.0538,0.4336,0.3186,0.4583,,,,,,0.5712,0.5566,,,,,,1,,,,,0.5]),
      loader: loadJSFXR
    },
    'sfx_denied': {
      data: jsfxr([0,,0.24,0.51,0.3829,0.15,,,,,,,,,,,,,1,,,,,0.5]),
      loader: loadJSFXR
    },
    'sfx_drop': {
      data: jsfxr([1,,0.0468,,0.2103,0.4979,,-0.4519,,,,,,,,,,,1,,,,,0.83]),
      loader: loadJSFXR
    },
    'bgm_game': {
      loader: loadSonant,
      data:
      {
    "endPattern": 382,
    "songData": [
        {
            "osc2_waveform": 0,
            "osc2_xenv": 0,
            "fx_pan_amt": 108,
            "osc2_vol": 0,
            "lfo_amt": 187,
            "lfo_osc1_freq": 0,
            "noise_fader": 60,
            "osc1_detune": 0,
            "osc2_oct": 8,
            "fx_filter": 1,
            "fx_resonance": 120,
            "fx_pan_freq": 5,
            "osc2_det": 0,
            "fx_delay_time": 4,
            "fx_freq": 10332,
            "lfo_waveform": 0,
            "osc1_vol": 0,
            "fx_delay_amt": 16,
            "osc1_waveform": 0,
            "notes": [
                147,
                0,
                0,
                0,
                147,
                0,
                0,
                0,
                147,
                0,
                0,
                0,
                147,
                0,
                0,
                0,
                147,
                0,
                0,
                0,
                147,
                0,
                0,
                0,
                147,
                0,
                0,
                0,
                147,
                0,
                0,
                0,
                147,
                0,
                0,
                0,
                147,
                0,
                0,
                0,
                147,
                0,
                0,
                0,
                147,
                0,
                0,
                0,
                147,
                0,
                0,
                0,
                147,
                0,
                0,
                0,
                147,
                0,
                0,
                0,
                147,
                0,
                0,
                0,
                147,
                0,
                0,
                0,
                147,
                0,
                0,
                0,
                147,
                0,
                0,
                0,
                147,
                0,
                0,
                0,
                147,
                0,
                0,
                0,
                147,
                0,
                0,
                0,
                147,
                0,
                0,
                0,
                147,
                0,
                0,
                0,
                147,
                0,
                0,
                0,
                147,
                0,
                0,
                0,
                147,
                0,
                0,
                0,
                147,
                0,
                0,
                0,
                147,
                0,
                0,
                0,
                147,
                0,
                0,
                0,
                147,
                0,
                0,
                0,
                147,
                0,
                0,
                0,
                147,
                0,
                0,
                0,
                147,
                0,
                0,
                0,
                147,
                0,
                0,
                0,
                147,
                0,
                0,
                0,
                147,
                0,
                0,
                0,
                147,
                0,
                0,
                0,
                147,
                0,
                0,
                0,
                147,
                0,
                0,
                0,
                147,
                0,
                0,
                0,
                147,
                0,
                0,
                0,
                147,
                0,
                0,
                0,
                147,
                0,
                0,
                0,
                147,
                0,
                0,
                0,
                147,
                0,
                0,
                0,
                147,
                0,
                0,
                0,
                147,
                0,
                0,
                0,
                147,
                0,
                0,
                0,
                147,
                0,
                0,
                0,
                147,
                0,
                0,
                0,
                147,
                0,
                0,
                0,
                147,
                0,
                0,
                0,
                147,
                0,
                0,
                0,
                147,
                0,
                0,
                0,
                147,
                0,
                0,
                0,
                147,
                0,
                0,
                0,
                147,
                0,
                0,
                0,
                147,
                0,
                0,
                0,
                147,
                0,
                0,
                0,
                147,
                0,
                0,
                0,
                147,
                0,
                0,
                0,
                147,
                0,
                0,
                0,
                147,
                0,
                0,
                0,
                147,
                0,
                0,
                0,
                147,
                0,
                0,
                0,
                147,
                0,
                0,
                0,
                147,
                0,
                0,
                0,
                147,
                0,
                0,
                0,
                147,
                0,
                0,
                0,
                147,
                0,
                0,
                0,
                147,
                0,
                0,
                0,
                147,
                0,
                0,
                0,
                147,
                0,
                0,
                0,
                147,
                0,
                0,
                0,
                147,
                0,
                0,
                0,
                147,
                0,
                0,
                0,
                147,
                0,
                0,
                0,
                147,
                0,
                0,
                0,
                147,
                0,
                0,
                0,
                147,
                0,
                0,
                0,
                147,
                0,
                0,
                0,
                147,
                0,
                0,
                0,
                147,
                0,
                0,
                0,
                147,
                0,
                0,
                0,
                147,
                0,
                0,
                0,
                147,
                0,
                0,
                0,
                147,
                0,
                0,
                0,
                147,
                0,
                0,
                0,
                147,
                0,
                0,
                0,
                147,
                0,
                0,
                0,
                147,
                0,
                0,
                0,
                147,
                0,
                0,
                0,
                147,
                0,
                0,
                0,
                147,
                0,
                0,
                0
            ],
            "lfo_fx_freq": 0,
            "osc2_detune": 0,
            "env_release": 4607,
            "env_sustain": 419,
            "osc1_xenv": 0,
            "lfo_freq": 5,
            "env_master": 130,
            "osc1_det": 0,
            "env_attack": 50,
            "osc1_oct": 8
        },
        {
            "osc2_waveform": 0,
            "osc2_xenv": 0,
            "fx_pan_amt": 0,
            "osc2_vol": 255,
            "lfo_amt": 96,
            "lfo_osc1_freq": 0,
            "noise_fader": 0,
            "osc1_detune": 0,
            "osc2_oct": 8,
            "fx_filter": 2,
            "fx_resonance": 60,
            "fx_pan_freq": 0,
            "osc2_det": 0,
            "fx_delay_time": 1,
            "fx_freq": 4067,
            "lfo_waveform": 0,
            "osc1_vol": 255,
            "fx_delay_amt": 45,
            "osc1_waveform": 0,
            "notes": [
                160,
                0,
                160,
                0,
                155,
                0,
                0,
                0,
                148,
                160,
                162,
                0,
                163,
                162,
                160,
                0,
                163,
                0,
                163,
                162,
                163,
                0,
                151,
                163,
                165,
                0,
                0,
                0,
                167,
                0,
                165,
                0,
                167,
                0,
                163,
                0,
                162,
                0,
                163,
                0,
                156,
                0,
                151,
                162,
                158,
                0,
                0,
                0,
                151,
                0,
                155,
                0,
                151,
                0,
                150,
                0,
                151,
                0,
                150,
                0,
                151,
                0,
                150,
                155,
                160,
                0,
                160,
                0,
                155,
                0,
                148,
                0,
                160,
                0,
                162,
                0,
                160,
                0,
                158,
                160,
                160,
                0,
                158,
                0,
                162,
                160,
                158,
                151,
                146,
                0,
                153,
                0,
                158,
                0,
                153,
                150,
                150,
                0,
                153,
                0,
                151,
                0,
                153,
                0,
                151,
                156,
                158,
                0,
                153,
                0,
                151,
                0,
                158,
                0,
                155,
                0,
                153,
                0,
                151,
                0,
                163,
                0,
                0,
                163,
                0,
                158,
                0,
                151,
                160,
                0,
                160,
                155,
                0,
                160,
                155,
                0,
                0,
                160,
                0,
                162,
                160,
                158,
                160,
                156,
                158,
                0,
                153,
                0,
                150,
                0,
                156,
                0,
                158,
                150,
                143,
                0,
                138,
                0,
                150,
                138,
                150,
                0,
                141,
                0,
                138,
                0,
                150,
                138,
                150,
                0,
                141,
                0,
                0,
                138,
                0,
                150,
                150,
                0,
                148,
                0,
                151,
                0,
                150,
                0,
                148,
                0,
                153,
                160,
                151,
                0,
                0,
                0,
                160,
                0,
                160,
                0,
                156,
                0,
                153,
                0,
                151,
                150,
                0,
                160,
                0,
                156,
                0,
                153,
                153,
                0,
                146,
                0,
                153,
                0,
                158,
                0,
                165,
                0,
                153,
                150,
                153,
                0,
                155,
                0,
                155,
                0,
                153,
                155,
                153,
                0,
                151,
                0,
                153,
                0,
                153,
                0,
                151,
                0,
                153,
                0,
                153,
                0,
                158,
                0,
                160,
                0,
                158,
                0,
                151,
                146,
                151,
                0,
                0,
                0,
                153,
                0,
                163,
                0,
                0,
                0,
                163,
                160,
                163,
                0,
                156,
                0,
                151,
                163,
                170,
                0,
                167,
                163,
                170,
                0,
                160,
                0,
                151,
                163,
                170,
                0,
                167,
                163,
                170,
                0,
                160,
                0,
                0,
                0,
                160,
                0,
                0,
                0,
                170,
                0,
                168,
                0,
                167,
                0,
                0,
                167,
                0,
                170,
                0,
                168,
                168,
                0,
                167,
                0,
                165,
                0,
                167,
                0,
                168,
                0,
                165,
                0,
                0,
                168,
                0,
                165,
                163,
                0,
                163,
                156,
                0,
                0,
                151,
                0,
                0,
                151,
                0,
                156,
                0,
                158,
                0,
                156,
                158,
                0,
                151,
                144,
                156,
                158,
                0,
                151,
                144,
                158,
                0,
                151,
                144,
                156,
                158,
                0,
                158,
                0,
                155,
                0,
                158,
                153,
                151,
                0,
                153,
                165,
                153,
                0,
                148,
                0,
                146,
                0,
                146,
                0,
                153,
                0,
                148,
                0,
                151,
                0,
                155,
                0,
                158,
                0,
                155,
                0
            ],
            "lfo_fx_freq": 1,
            "osc2_detune": 0,
            "env_release": 13163,
            "env_sustain": 0,
            "osc1_xenv": 0,
            "lfo_freq": 3,
            "env_master": 255,
            "osc1_det": 0,
            "env_attack": 22,
            "osc1_oct": 7
        },
        {
            "osc2_waveform": 2,
            "osc2_xenv": 0,
            "fx_pan_amt": 0,
            "osc2_vol": 157,
            "lfo_amt": 0,
            "lfo_osc1_freq": 0,
            "noise_fader": 0,
            "osc1_detune": 0,
            "osc2_oct": 6,
            "fx_filter": 2,
            "fx_resonance": 76,
            "fx_pan_freq": 2,
            "osc2_det": 0,
            "fx_delay_time": 3,
            "fx_freq": 3900,
            "lfo_waveform": 0,
            "osc1_vol": 192,
            "fx_delay_amt": 0,
            "osc1_waveform": 2,
            "notes": [
                160,
                0,
                148,
                0,
                160,
                0,
                148,
                0,
                160,
                172,
                148,
                160,
                172,
                172,
                148,
                0,
                146,
                0,
                170,
                0,
                158,
                158,
                170,
                146,
                158,
                158,
                158,
                146,
                158,
                146,
                0,
                156,
                168,
                156,
                168,
                156,
                0,
                168,
                156,
                156,
                0,
                168,
                0,
                144,
                0,
                144,
                0,
                155,
                0,
                143,
                167,
                167,
                0,
                167,
                155,
                155,
                155,
                167,
                155,
                143,
                0,
                160,
                160,
                148,
                160,
                148,
                172,
                148,
                0,
                160,
                0,
                160,
                172,
                148,
                0,
                148,
                0,
                146,
                0,
                158,
                0,
                158,
                158,
                170,
                170,
                146,
                170,
                170,
                158,
                158,
                158,
                158,
                156,
                0,
                156,
                0,
                144,
                168,
                156,
                168,
                144,
                168,
                156,
                156,
                144,
                156,
                156,
                0,
                155,
                0,
                143,
                155,
                143,
                0,
                155,
                143,
                167,
                155,
                155,
                143,
                167,
                143,
                0,
                160,
                172,
                172,
                160,
                160,
                148,
                172,
                160,
                0,
                148,
                0,
                160,
                0,
                160,
                0,
                158,
                0,
                158,
                0,
                158,
                146,
                0,
                158,
                158,
                158,
                0,
                158,
                0,
                146,
                0,
                168,
                156,
                168,
                168,
                168,
                144,
                156,
                168,
                156,
                168,
                156,
                0,
                144,
                0,
                143,
                155,
                143,
                155,
                143,
                167,
                143,
                155,
                167,
                0,
                155,
                0,
                155,
                0,
                155,
                0,
                148,
                160,
                160,
                0,
                172,
                0,
                148,
                0,
                160,
                160,
                148,
                0,
                160,
                160,
                0,
                146,
                0,
                170,
                0,
                158,
                0,
                146,
                0,
                158,
                0,
                146,
                0,
                146,
                0,
                158,
                0,
                156,
                156,
                156,
                0,
                144,
                0,
                168,
                168,
                144,
                0,
                156,
                168,
                156,
                156,
                144,
                0,
                143,
                155,
                143,
                0,
                143,
                0,
                155,
                0,
                143,
                155,
                167,
                167,
                155,
                0,
                143,
                0,
                151,
                0,
                163,
                0,
                151,
                0,
                151,
                0,
                163,
                0,
                151,
                0,
                151,
                163,
                151,
                0,
                160,
                0,
                148,
                0,
                172,
                160,
                148,
                0,
                160,
                172,
                148,
                160,
                148,
                0,
                160,
                0,
                144,
                168,
                168,
                168,
                144,
                0,
                156,
                156,
                156,
                0,
                156,
                0,
                144,
                168,
                168,
                158,
                0,
                158,
                0,
                146,
                0,
                158,
                0,
                158,
                0,
                158,
                170,
                146,
                158,
                158,
                0,
                151,
                0,
                163,
                175,
                175,
                0,
                163,
                163,
                163,
                151,
                175,
                151,
                0,
                151,
                0,
                160,
                0,
                148,
                0,
                148,
                0,
                160,
                172,
                148,
                0,
                148,
                0,
                160,
                0,
                148,
                0,
                156,
                0,
                144,
                156,
                144,
                168,
                156,
                168,
                144,
                0,
                156,
                0,
                156,
                0,
                144,
                0,
                158,
                170,
                158,
                0,
                158,
                0,
                158,
                0,
                170,
                0,
                158,
                170
            ],
            "lfo_fx_freq": 1,
            "osc2_detune": 0,
            "env_release": 12631,
            "env_sustain": 2418,
            "osc1_xenv": 0,
            "lfo_freq": 0,
            "env_master": 139,
            "osc1_det": 0,
            "env_attack": 0,
            "osc1_oct": 5
        }
    ],
    "rowLen": 1739,
    "songLen": 46
    }
    }
  }
};

window.onload = function() {
  var fontHack = document.getElementById('fontHack');
  fontHack.parentNode.removeChild(fontHack);

  kz.initialize('canvas');
  kz.run(scene_loading);

  kz.loadResources(resources).then(function () {
    console.log("Loaded resources!");
    kz.run(scene_main_menu);
    setInterval(function () {
      incrementRecord('total_time', 1);
    }, 1000);
  });
};
/**
 * Records to store:
 * 1. Number of games played (play_count)
 * 2. Total time spent playing in seconds (total_time)
 * 3. Highscore in one game (max_score)
 * 4. Highest level gotten to (max_level)
 * 5. Total number of zodiac abilities activated (total_zodiac)
 * 6. Maximum number of zodiac abilities activated in one game (max_zodiac)
 * 7. Number of orbs shot (total_orbs)
 * 8. Maximum number of white orbs ever shot in a row (max_white_orbs)
 * 9. Maximum number of black orbs ever shot in a row (max_black_orbs)
 * 10. Maximum number of zodiac orbs ever shot in a row (max_zodiac_orbs)
 * 11. Maximum number of rows cleared in one game (max_rows)
 * 12. Total number of rows cleared ever (total_rows)
 * 13. Maximum time survived in one single game in seconds (max_time)
 */
var records = [
  {text: 'GAMES PLAYED', name:'play_count'},
  {text: 'TOTAL TIME SPENT', name:'total_time'},
  {text: 'LONGEST TIME SURVIVED', name: 'max_time'},
  {text: 'HIGHEST SCORE OBTAINED', name:'max_score'},
  {text: 'HIGHEST LEVEL REACHED', name:'max_level'},
  {text: 'TOTAL ROWS CLEARED', name: 'total_rows'},
  {text: 'MOST ROWS CLEARED IN ONE GAME', name: 'max_rows'},
  {text: 'TOTAL ZODIAC CLEARS', name:'total_zodiac'},
  {text: 'MOST ZODIACS CLEARS IN ONE GAME', name:'max_zodiac'},
  {text: 'TOTAL ORBS SHOT', name:'total_orbs'},
  {text: 'MAX CONSECUTIVE WHITE ORBS', name:'max_white_orbs'},
  {text: 'MAX CONSECUTIVE BLACK ORBS', name:'max_black_orbs'},
  {text: 'MAX CONSECUTIVE ZODIAC ORBS', name:'max_zodiac_orbs'}];
(function() {
  records.forEach(function (record) {
    if (!localStorage.getItem(record.name)) {
      localStorage.setItem(record.name, '0');
    }
  });
})();

function incrementRecord(name, value) {
  localStorage.setItem(
    name,
    parseInt(localStorage.getItem(name), 10) + value);
}

function maxRecord(name, value) {
  localStorage.setItem(
    name,
    Math.max(parseInt(localStorage.getItem(name), 10), value));
}

function getRecord(name) {
  return parseInt(localStorage.getItem(name),10);
}
