// Globals(prefixed with $):
// $x -- sonantx


function lj(data, resolve) { //loadJSFXR
  var buff = base64ToArrayBuffer(data.substr(22));
  kz.a.decodeAudioData(buff, resolve);
}

function ls(data, resolve) { //loadsonant
  var songGen = new $x.M(data);
  songGen.createAudioBuffer(resolve);
}

var resources = {
  i: {
    a: {x:36,y:263,w:32,h:32}, //background
    b: {x:0,y:0,w:50,h:50,W:37,H:39,f:1}, //character_boar
    c: {x:37,y:0,w:50,h:50,W:42,H:38,f:1}, //character_cat
    d: {x:0,y:39,w:50,h:50,W:40,H:42,f:1}, //character_dog
    e: {x:40,y:38,w:50,h:50,W:45,H:40,f:1}, //character_dragon
    f: {x:0,y:81,w:50,h:50,W:35,H:40,f:1}, //character_hare
    g: {x:35,y:81,w:50,h:50,W:41,H:43,f:1}, //character_horse
    h: {x:0,y:121,w:50,h:50,W:30,H:44,f:1}, //character_monkey
    i: {x:30,y:124,w:50,h:50,W:42,H:32,f:1}, //character_ox
    k: {x:0,y:165,w:50,h:50,W:41,H:39,f:1}, //character_rat
    l: {x:41,y:156,w:50,h:50,W:35,H:36,f:1}, //character_rooster
    m: {x:0,y:205,w:50,h:50,W:43,H:43,f:1}, //character_sheep
    n: {x:43,y:192,w:50,h:50,W:34,H:34,f:1}, //character_snake
    o: {x:0,y:248,w:50,h:50,W:36,H:41,f:1}, //chraacter_tiger
    p: {x:43,y:226,w:50,h:50,W:21,H:37,f:1}, //character_random
    r: {x:65,y:226,w:17,h:17}, // piece_black
    s: {x:64,y:243,w:17,h:17}, // piece_white
    t: {x:72,y:124,w:17,h:17}, //piece_zodiac
    u: {x:68,y:260,w:9,h:22,W:9,H:22,f:1}, //shooter_0
    v: {x:76,y:81,w:9,h:22,W:5,H:22,f:1}, // shooter_1
    w: {x:76,y:156,w:9,h:22,W:1,H:22,f:1} //shooter_2
  },
  sounds: {
    'sfx_shoot': {
      data: jsfxr([0,,0.1881,,0.3164,0.8042,0.2,-0.2915,,,,,,0.4661,0.156,,0.1754,-0.182,1,,,0.1755,,0.5]),
      loader: lj
    },
    'sfx_clear': {
      data: jsfxr([1,,0.06,0.4848,0.4938,0.8917,,,,,,,,,,,,,1,,,,,0.49]),
      loader: lj
    },
    'sfx_select': {
      data: jsfxr([0,,0.0538,0.4336,0.3186,0.4583,,,,,,0.5712,0.5566,,,,,,1,,,,,0.5]),
      loader: lj
    },
    'sfx_denied': {
      data: jsfxr([0,,0.24,0.51,0.3829,0.15,,,,,,,,,,,,,1,,,,,0.5]),
      loader: lj
    },
    'sfx_drop': {
      data: jsfxr([1,,0.0468,,0.2103,0.4979,,-0.4519,,,,,,,,,,,1,,,,,0.83]),
      loader: lj
    },
    'bgm_game': {
      loader: ls,
      data:
      {
    "endPattern": 382,
    "songData": [
        {
            "a": 0,
            "b": 0,
            "c": 108,
            "d": 0,
            "e": 187,
            "f": 0,
            "g": 60,
            "h": 0,
            "i": 8,
            "j": 1,
            "k": 120,
            "l": 5,
            "m": 0,
            "n": 4,
            "o": 10332,
            "p": 0,
            "r": 0,
            "s": 16,
            "t": 0,
            "notes": [
                147,
                0,
                0,
                0,
                147,
                0,
                0,
                0,
                147,
                0,
                0,
                0,
                147,
                0,
                0,
                0,
                147,
                0,
                0,
                0,
                147,
                0,
                0,
                0,
                147,
                0,
                0,
                0,
                147,
                0,
                0,
                0,
                147,
                0,
                0,
                0,
                147,
                0,
                0,
                0,
                147,
                0,
                0,
                0,
                147,
                0,
                0,
                0,
                147,
                0,
                0,
                0,
                147,
                0,
                0,
                0,
                147,
                0,
                0,
                0,
                147,
                0,
                0,
                0,
                147,
                0,
                0,
                0,
                147,
                0,
                0,
                0,
                147,
                0,
                0,
                0,
                147,
                0,
                0,
                0,
                147,
                0,
                0,
                0,
                147,
                0,
                0,
                0,
                147,
                0,
                0,
                0,
                147,
                0,
                0,
                0,
                147,
                0,
                0,
                0,
                147,
                0,
                0,
                0,
                147,
                0,
                0,
                0,
                147,
                0,
                0,
                0,
                147,
                0,
                0,
                0,
                147,
                0,
                0,
                0,
                147,
                0,
                0,
                0,
                147,
                0,
                0,
                0,
                147,
                0,
                0,
                0,
                147,
                0,
                0,
                0,
                147,
                0,
                0,
                0,
                147,
                0,
                0,
                0,
                147,
                0,
                0,
                0,
                147,
                0,
                0,
                0,
                147,
                0,
                0,
                0,
                147,
                0,
                0,
                0,
                147,
                0,
                0,
                0,
                147,
                0,
                0,
                0,
                147,
                0,
                0,
                0,
                147,
                0,
                0,
                0,
                147,
                0,
                0,
                0,
                147,
                0,
                0,
                0,
                147,
                0,
                0,
                0,
                147,
                0,
                0,
                0,
                147,
                0,
                0,
                0,
                147,
                0,
                0,
                0,
                147,
                0,
                0,
                0,
                147,
                0,
                0,
                0,
                147,
                0,
                0,
                0,
                147,
                0,
                0,
                0,
                147,
                0,
                0,
                0,
                147,
                0,
                0,
                0,
                147,
                0,
                0,
                0,
                147,
                0,
                0,
                0,
                147,
                0,
                0,
                0,
                147,
                0,
                0,
                0,
                147,
                0,
                0,
                0,
                147,
                0,
                0,
                0,
                147,
                0,
                0,
                0,
                147,
                0,
                0,
                0,
                147,
                0,
                0,
                0,
                147,
                0,
                0,
                0,
                147,
                0,
                0,
                0,
                147,
                0,
                0,
                0,
                147,
                0,
                0,
                0,
                147,
                0,
                0,
                0,
                147,
                0,
                0,
                0,
                147,
                0,
                0,
                0,
                147,
                0,
                0,
                0,
                147,
                0,
                0,
                0,
                147,
                0,
                0,
                0,
                147,
                0,
                0,
                0,
                147,
                0,
                0,
                0,
                147,
                0,
                0,
                0,
                147,
                0,
                0,
                0,
                147,
                0,
                0,
                0,
                147,
                0,
                0,
                0,
                147,
                0,
                0,
                0,
                147,
                0,
                0,
                0,
                147,
                0,
                0,
                0,
                147,
                0,
                0,
                0,
                147,
                0,
                0,
                0,
                147,
                0,
                0,
                0,
                147,
                0,
                0,
                0,
                147,
                0,
                0,
                0,
                147,
                0,
                0,
                0,
                147,
                0,
                0,
                0,
                147,
                0,
                0,
                0,
                147,
                0,
                0,
                0,
                147,
                0,
                0,
                0,
                147,
                0,
                0,
                0
            ],
            "u": 0,
            "v": 0,
            "w": 4607,
            "x": 419,
            "y": 0,
            "z": 5,
            "_": 130,
            "aa": 0,
            "ab": 50,
            "ac": 8
        },
        {
            "a": 0,
            "b": 0,
            "c": 0,
            "d": 255,
            "e": 96,
            "f": 0,
            "g": 0,
            "h": 0,
            "i": 8,
            "j": 2,
            "k": 60,
            "l": 0,
            "m": 0,
            "n": 1,
            "o": 4067,
            "p": 0,
            "r": 255,
            "s": 45,
            "t": 0,
            "notes": [
                160,
                0,
                160,
                0,
                155,
                0,
                0,
                0,
                148,
                160,
                162,
                0,
                163,
                162,
                160,
                0,
                163,
                0,
                163,
                162,
                163,
                0,
                151,
                163,
                165,
                0,
                0,
                0,
                167,
                0,
                165,
                0,
                167,
                0,
                163,
                0,
                162,
                0,
                163,
                0,
                156,
                0,
                151,
                162,
                158,
                0,
                0,
                0,
                151,
                0,
                155,
                0,
                151,
                0,
                150,
                0,
                151,
                0,
                150,
                0,
                151,
                0,
                150,
                155,
                160,
                0,
                160,
                0,
                155,
                0,
                148,
                0,
                160,
                0,
                162,
                0,
                160,
                0,
                158,
                160,
                160,
                0,
                158,
                0,
                162,
                160,
                158,
                151,
                146,
                0,
                153,
                0,
                158,
                0,
                153,
                150,
                150,
                0,
                153,
                0,
                151,
                0,
                153,
                0,
                151,
                156,
                158,
                0,
                153,
                0,
                151,
                0,
                158,
                0,
                155,
                0,
                153,
                0,
                151,
                0,
                163,
                0,
                0,
                163,
                0,
                158,
                0,
                151,
                160,
                0,
                160,
                155,
                0,
                160,
                155,
                0,
                0,
                160,
                0,
                162,
                160,
                158,
                160,
                156,
                158,
                0,
                153,
                0,
                150,
                0,
                156,
                0,
                158,
                150,
                143,
                0,
                138,
                0,
                150,
                138,
                150,
                0,
                141,
                0,
                138,
                0,
                150,
                138,
                150,
                0,
                141,
                0,
                0,
                138,
                0,
                150,
                150,
                0,
                148,
                0,
                151,
                0,
                150,
                0,
                148,
                0,
                153,
                160,
                151,
                0,
                0,
                0,
                160,
                0,
                160,
                0,
                156,
                0,
                153,
                0,
                151,
                150,
                0,
                160,
                0,
                156,
                0,
                153,
                153,
                0,
                146,
                0,
                153,
                0,
                158,
                0,
                165,
                0,
                153,
                150,
                153,
                0,
                155,
                0,
                155,
                0,
                153,
                155,
                153,
                0,
                151,
                0,
                153,
                0,
                153,
                0,
                151,
                0,
                153,
                0,
                153,
                0,
                158,
                0,
                160,
                0,
                158,
                0,
                151,
                146,
                151,
                0,
                0,
                0,
                153,
                0,
                163,
                0,
                0,
                0,
                163,
                160,
                163,
                0,
                156,
                0,
                151,
                163,
                170,
                0,
                167,
                163,
                170,
                0,
                160,
                0,
                151,
                163,
                170,
                0,
                167,
                163,
                170,
                0,
                160,
                0,
                0,
                0,
                160,
                0,
                0,
                0,
                170,
                0,
                168,
                0,
                167,
                0,
                0,
                167,
                0,
                170,
                0,
                168,
                168,
                0,
                167,
                0,
                165,
                0,
                167,
                0,
                168,
                0,
                165,
                0,
                0,
                168,
                0,
                165,
                163,
                0,
                163,
                156,
                0,
                0,
                151,
                0,
                0,
                151,
                0,
                156,
                0,
                158,
                0,
                156,
                158,
                0,
                151,
                144,
                156,
                158,
                0,
                151,
                144,
                158,
                0,
                151,
                144,
                156,
                158,
                0,
                158,
                0,
                155,
                0,
                158,
                153,
                151,
                0,
                153,
                165,
                153,
                0,
                148,
                0,
                146,
                0,
                146,
                0,
                153,
                0,
                148,
                0,
                151,
                0,
                155,
                0,
                158,
                0,
                155,
                0
            ],
            "u": 1,
            "v": 0,
            "w": 13163,
            "x": 0,
            "y": 0,
            "z": 3,
            "_": 255,
            "aa": 0,
            "ab": 22,
            "ac": 7
        },
        {
            "a": 2,
            "b": 0,
            "c": 0,
            "d": 157,
            "e": 0,
            "f": 0,
            "g": 0,
            "h": 0,
            "i": 6,
            "j": 2,
            "k": 76,
            "l": 2,
            "m": 0,
            "n": 3,
            "o": 3900,
            "p": 0,
            "r": 192,
            "s": 0,
            "t": 2,
            "notes": [
                160,
                0,
                148,
                0,
                160,
                0,
                148,
                0,
                160,
                172,
                148,
                160,
                172,
                172,
                148,
                0,
                146,
                0,
                170,
                0,
                158,
                158,
                170,
                146,
                158,
                158,
                158,
                146,
                158,
                146,
                0,
                156,
                168,
                156,
                168,
                156,
                0,
                168,
                156,
                156,
                0,
                168,
                0,
                144,
                0,
                144,
                0,
                155,
                0,
                143,
                167,
                167,
                0,
                167,
                155,
                155,
                155,
                167,
                155,
                143,
                0,
                160,
                160,
                148,
                160,
                148,
                172,
                148,
                0,
                160,
                0,
                160,
                172,
                148,
                0,
                148,
                0,
                146,
                0,
                158,
                0,
                158,
                158,
                170,
                170,
                146,
                170,
                170,
                158,
                158,
                158,
                158,
                156,
                0,
                156,
                0,
                144,
                168,
                156,
                168,
                144,
                168,
                156,
                156,
                144,
                156,
                156,
                0,
                155,
                0,
                143,
                155,
                143,
                0,
                155,
                143,
                167,
                155,
                155,
                143,
                167,
                143,
                0,
                160,
                172,
                172,
                160,
                160,
                148,
                172,
                160,
                0,
                148,
                0,
                160,
                0,
                160,
                0,
                158,
                0,
                158,
                0,
                158,
                146,
                0,
                158,
                158,
                158,
                0,
                158,
                0,
                146,
                0,
                168,
                156,
                168,
                168,
                168,
                144,
                156,
                168,
                156,
                168,
                156,
                0,
                144,
                0,
                143,
                155,
                143,
                155,
                143,
                167,
                143,
                155,
                167,
                0,
                155,
                0,
                155,
                0,
                155,
                0,
                148,
                160,
                160,
                0,
                172,
                0,
                148,
                0,
                160,
                160,
                148,
                0,
                160,
                160,
                0,
                146,
                0,
                170,
                0,
                158,
                0,
                146,
                0,
                158,
                0,
                146,
                0,
                146,
                0,
                158,
                0,
                156,
                156,
                156,
                0,
                144,
                0,
                168,
                168,
                144,
                0,
                156,
                168,
                156,
                156,
                144,
                0,
                143,
                155,
                143,
                0,
                143,
                0,
                155,
                0,
                143,
                155,
                167,
                167,
                155,
                0,
                143,
                0,
                151,
                0,
                163,
                0,
                151,
                0,
                151,
                0,
                163,
                0,
                151,
                0,
                151,
                163,
                151,
                0,
                160,
                0,
                148,
                0,
                172,
                160,
                148,
                0,
                160,
                172,
                148,
                160,
                148,
                0,
                160,
                0,
                144,
                168,
                168,
                168,
                144,
                0,
                156,
                156,
                156,
                0,
                156,
                0,
                144,
                168,
                168,
                158,
                0,
                158,
                0,
                146,
                0,
                158,
                0,
                158,
                0,
                158,
                170,
                146,
                158,
                158,
                0,
                151,
                0,
                163,
                175,
                175,
                0,
                163,
                163,
                163,
                151,
                175,
                151,
                0,
                151,
                0,
                160,
                0,
                148,
                0,
                148,
                0,
                160,
                172,
                148,
                0,
                148,
                0,
                160,
                0,
                148,
                0,
                156,
                0,
                144,
                156,
                144,
                168,
                156,
                168,
                144,
                0,
                156,
                0,
                156,
                0,
                144,
                0,
                158,
                170,
                158,
                0,
                158,
                0,
                158,
                0,
                170,
                0,
                158,
                170
            ],
            "u": 1,
            "v": 0,
            "w": 12631,
            "x": 2418,
            "y": 0,
            "z": 0,
            "_": 139,
            "aa": 0,
            "ab": 0,
            "ac": 5
        }
    ],
    "rowLen": 1739,
    "songLen": 46
    }
    }
  }
};

$W.onload = function() {
  var fontHack = $D.getElementById('fontHack');
  fontHack.parentNode.removeChild(fontHack);

  kz.initialize('canvas');
  kz.run(scene_loading);

  kz.L(resources).then(function () {
    kz.run(scene_main_menu);
    setInterval(function () {
      incrementRecord('total_time', 1);
    }, 1000);
  });
};
/**
 * Records to store:
 * 1. Number of games played (play_count)
 * 2. Total time spent playing in seconds (total_time)
 * 3. Highscore in one game (max_score)
 * 4. Highest level gotten to (max_level)
 * 5. Total number of zodiac abilities activated (total_zodiac)
 * 6. Maximum number of zodiac abilities activated in one game (max_zodiac)
 * 7. Number of orbs shot (total_orbs)
 * 8. Maximum number of white orbs ever shot in a row (max_white_orbs)
 * 9. Maximum number of black orbs ever shot in a row (max_black_orbs)
 * 10. Maximum number of zodiac orbs ever shot in a row (max_zodiac_orbs)
 * 11. Maximum number of rows cleared in one game (max_rows)
 * 12. Total number of rows cleared ever (total_rows)
 * 13. Maximum time survived in one single game in seconds (max_time)
 */
var records = [
  {text: 'GAMES PLAYED', name:'play_count'},
  {text: 'TOTAL TIME SPENT', name:'total_time'},
  {text: 'LONGEST TIME SURVIVED', name: 'max_time'},
  {text: 'HIGHEST SCORE OBTAINED', name:'max_score'},
  {text: 'HIGHEST LEVEL REACHED', name:'max_level'},
  {text: 'TOTAL ROWS CLEARED', name: 'total_rows'},
  {text: 'MOST ROWS CLEARED IN ONE GAME', name: 'max_rows'},
  {text: 'TOTAL ZODIAC CLEARS', name:'total_zodiac'},
  {text: 'MOST ZODIACS CLEARS IN ONE GAME', name:'max_zodiac'},
  {text: 'TOTAL ORBS SHOT', name:'total_orbs'},
  {text: 'MAX CONSECUTIVE WHITE ORBS', name:'max_white_orbs'},
  {text: 'MAX CONSECUTIVE BLACK ORBS', name:'max_black_orbs'},
  {text: 'MAX CONSECUTIVE ZODIAC ORBS', name:'max_zodiac_orbs'}];
(function() {
  records.forEach(function (record) {
    if (!localStorage.getItem(record.name)) {
      localStorage.setItem(record.name, '0');
    }
  });
})();

function incrementRecord(name, value) {
  localStorage.setItem(
    name,
    parseInt(localStorage.getItem(name), 10) + value);
}

function maxRecord(name, value) {
  localStorage.setItem(
    name,
    Math.max(parseInt(localStorage.getItem(name), 10), value));
}

function getRecord(name) {
  return parseInt(localStorage.getItem(name),10);
}
