function ca(){this.Da=function(a){for(var c=0;24>c;c++)this[String.fromCharCode(97+c)]=a[c]||0;.01>this.c&&(this.c=.01);a=this.b+this.c+this.e;.18>a&&(a=.18/a,this.b*=a,this.c*=a,this.e*=a)}}
var da=new function(){this.Y=new ca;var a,c,e,f,t,q,u,G,Z,N,g,b;this.reset=function(){var a=this.Y;f=100/(a.f*a.f+.001);t=100/(a.g*a.g+.001);q=1-a.h*a.h*a.h*.01;u=-a.i*a.i*a.i*1E-6;a.a||(g=.5-a.n/2,b=5E-5*-a.o);G=1+a.l*a.l*(0<a.l?-.9:10);Z=0;N=1==a.m?0:(1-a.m)*(1-a.m)*2E4+32};this.Ha=function(){this.reset();var b=this.Y;a=b.b*b.b*1E5;c=b.c*b.c*1E5;e=b.e*b.e*1E5+12;return 3*((a+c+e)/3|0)};this.Ga=function(k,v){var h=this.Y,H=1!=h.s||h.v,K=h.v*h.v*.1,O=1+3E-4*h.w,y=h.s*h.s*h.s*.1,wa=1+1E-4*h.t,l=1!=
h.s,xa=h.x*h.x,ya=h.g,ma=h.q||h.r,F=h.r*h.r*h.r*.2,C=h.q*h.q*(0>h.q?-1020:1020),z=h.p?((1-h.p)*(1-h.p)*2E4|0)+32:0,D=h.d,na=h.j/2,za=h.k*h.k*.01,ea=h.a,fa=a,Aa=1/a,Ba=1/c,Ca=1/e,h=5/(1+h.u*h.u*20)*(.01+y);.8<h&&(h=.8);for(var h=1-h,ga=!1,oa=0,T=0,U=0,aa=0,P=0,V,Q=0,w,I=0,L,ha=0,m,pa=0,J,ia=0,ba=Array(1024),W=Array(32),E=ba.length;E--;)ba[E]=0;for(E=W.length;E--;)W[E]=2*Math.random()-1;for(E=0;E<v;E++){if(ga)return E;z&&++pa>=z&&(pa=0,this.reset());N&&++Z>=N&&(N=0,f*=G);q+=u;f*=q;f>t&&(f=t,0<ya&&(ga=
!0));w=f;0<na&&(ia+=za,w*=1+Math.sin(ia)*na);w|=0;8>w&&(w=8);ea||(g+=b,0>g?g=0:.5<g&&(g=.5));if(++T>fa)switch(T=0,++oa){case 1:fa=c;break;case 2:fa=e}switch(oa){case 0:U=T*Aa;break;case 1:U=1+2*(1-T*Ba)*D;break;case 2:U=1-T*Ca;break;case 3:U=0,ga=!0}ma&&(C+=F,L=C|0,0>L?L=-L:1023<L&&(L=1023));H&&O&&(K*=O,1E-5>K?K=1E-5:.1<K&&(K=.1));J=0;for(var Da=8;Da--;){I++;if(I>=w&&(I%=w,3==ea))for(V=W.length;V--;)W[V]=2*Math.random()-1;switch(ea){case 0:m=I/w<g?.5:-.5;break;case 1:m=1-I/w*2;break;case 2:m=I/w;
m=6.28318531*(.5<m?m-1:m);m=1.27323954*m+.405284735*m*m*(0>m?1:-1);m=.225*((0>m?-1:1)*m*m-m)+m;break;case 3:m=W[Math.abs(32*I/w|0)]}H&&(V=Q,y*=wa,0>y?y=0:.1<y&&(y=.1),l?(P+=(m-Q)*y,P*=h):(Q=m,P=0),Q+=P,aa+=Q-V,m=aa*=1-K);ma&&(ba[ha%1024]=m,m+=ba[(ha-L+1024)%1024],ha++);J+=m}J=.125*J*U*xa;k[E]=1<=J?32767:-1>=J?-32768:32767*J|0}return v}};
window.jsfxr=function(a){da.Y.Da(a);var c=da.Ha();a=new Uint8Array(4*((c+1)/2|0)+44);var c=2*da.Ga(new Uint16Array(a.buffer,44),c),e=new Uint32Array(a.buffer,0,44);e[0]=1179011410;e[1]=c+36;e[2]=1163280727;e[3]=544501094;e[4]=16;e[5]=65537;e[6]=44100;e[7]=88200;e[8]=1048578;e[9]=1635017060;e[10]=c;for(var c=c+44,e=0,f="data:audio/wav;base64,";e<c;e+=3)var t=a[e]<<16|a[e+1]<<8|a[e+2],f=f+("ABCDEFGHIJKLMNOPQRSTUVWXYZabcdefghijklmnopqrstuvwxyz0123456789+/"[t>>18]+"ABCDEFGHIJKLMNOPQRSTUVWXYZabcdefghijklmnopqrstuvwxyz0123456789+/"[t>>
12&63]+"ABCDEFGHIJKLMNOPQRSTUVWXYZabcdefghijklmnopqrstuvwxyz0123456789+/"[t>>6&63]+"ABCDEFGHIJKLMNOPQRSTUVWXYZabcdefghijklmnopqrstuvwxyz0123456789+/"[t&63]);return f};var d,ja,n,p,r,x,ka;function la(a){var c={},e=[],f;for(f in a)e.push(new Promise(function(e){c[f]=new Image;c[f].addEventListener("load",e);c[f].src=a[f]}));return Promise.all(e).then(function(){d.images=c;return d.images})}
function qa(a){ja=new AudioContext;var c={},e=[],f;for(f in a)e.push(new Promise(function(e){var q=f,u=new XMLHttpRequest;u.open("GET",a[q],!0);u.responseType="arraybuffer";u.onload=function(){ja.decodeAudioData(u.response,function(a){c[q]={play:function(){var a=ja.createBufferSource();a.buffer=this.buffer;a.connect(ja.destination);a.start(0)},buffer:a};e()})};u.send()}));return Promise.all(e).then(function(){d.da=c;return d.da})}for(var ra={},sa=0;256>sa;sa++)ra[sa]=0;var A={};
function B(a){var c=performance.now(),e=a.object[a.J],f=a.value,t=a.duration?a.duration:Math.abs(f-e)/a.ca;return new Promise(function(q){function u(){var G=(performance.now()-c)/t;1<=G?(a.object[a.J]=f,q()):(a.object[a.J]=G*f+(1-G)*e,window.requestAnimationFrame(u))}window.requestAnimationFrame(u)})}var M=[],ta=0;
function R(a){for(name in a)a.hasOwnProperty(name)&&(this[name]=a[name]);if("number"!==typeof this.x)throw"Entity.x must be a number";if("number"!==typeof this.y)throw"Entity.y must be a number";if("function"!==typeof this.ha)throw"Entity.listen must be a function";this.la=ta;n[this.la]=this;ta++}R.prototype.x=0;R.prototype.y=0;R.prototype.ha=function(){};R.prototype["delete"]=function(){delete n[this.la]};
function S(a){a="undefined"!==typeof a?a:{};if("function"===typeof a.P)throw this.P=a.P,"Scene.initialize must be function";if("function"===typeof a.R)throw this.R=a.R,"Scene.preUpdate must be function";if("function"===typeof a.X)throw this.X=a.X,"Scene.postUpdate must be function";if("function"===typeof a.M)throw this.M=a.M,"Scene.draw must be function";}S.prototype.P=function(){};S.prototype.R=function(){};S.prototype.X=function(){};S.prototype.M=function(){};
function ua(){p=document.getElementById("canvas");r=p.getContext("2d");r.Z=function(){r.clearRect(0,0,p.width,p.height)}}
function va(){ua();document.addEventListener("keydown",function(a){a.preventDefault();0==ra[a.which]?(ra[a.which]=1,a.L="keypress"):a.L="keyheld";M.push(a)});document.addEventListener("keyup",function(a){a.preventDefault();a.L="keyup";ra[a.which]=0;M.push(a)});document.addEventListener("touchstart",function(a){a.preventDefault();for(var c=0;c<a.touches.length;c++){var e=a.touches[c];A[e.identifier]||(A[e.identifier]={pa:e,current:e})}console.log("touchstart:",a,JSON.stringify(A))});document.addEventListener("touchmove",
function(a){a.preventDefault();for(var c=0;c<a.touches.length;c++){var e=a.touches[c];A[e.identifier]&&(A[e.identifier].current=e)}console.log("touchmove:",a,JSON.stringify(A))});document.addEventListener("touchend",function(a){a.preventDefault();for(var c in A){for(var e=!1,f=0;f<a.touches.length;f++)a.touches[f].identifier==c&&(e=!0);if(!e){var e=A[c].pa.screenX,f=A[c].pa.screenY,t=A[c].current.screenX,q=A[c].current.screenY;20>Math.abs(e-t)+Math.abs(f-q)?M.push({L:"keypress",which:90}):40>Math.abs(f-
q)&&20<e-t?M.push({L:"keypress",which:37}):40>Math.abs(f-q)&&20<t-e&&M.push({L:"keypress",which:39});delete A[c]}}console.log("touchend:",a,JSON.stringify(A))})}function Ea(){x.R(X.now());x.M(X.now());x.X(X.now());window.requestAnimationFrame(Ea)}function Fa(a){if(void 0===a||null===a||"function"!==typeof a.P||"function"!==typeof a.R||"function"!==typeof a.X||"function"!==typeof a.M)throw"No scene attached!";n={};x=a;x.P();window.requestAnimationFrame(Ea)}var X=Object.create(performance);X.ia=0;
X.now=function(){return Y?ka:performance.now()-X.ia};var Y=!1,Ga=0;function Ha(){X.ia+=performance.now()-Ga;Y=!1}
var Ja=function(){var a=new S,c;a.P=function(){c={ja:!0,blink:!0,ka:1}};a.M=function(){r.Z();r.save();r.fillStyle="#290000";r.fillRect(0,0,p.width,p.height);r.restore();r.save();r.globalAlpha=c.ka;r.textAlign="center";r.textBaseline="center";r.font="48px silom";r.strokeStyle="#ce0000";r.fillStyle="#ffa100";r.lineWidth=6;r.strokeText("MONSTERS",p.width/2,110);r.fillText("MONSTERS",p.width/2,110);r.strokeText("REVERSED",p.width/2,170);r.fillText("REVERSED",p.width/2,170);r.restore();c.ja&&(r.save(),
r.globalAlpha=c.ka,r.textAlign="center",r.textBaseline="center",r.font="24px silom",r.fillStyle="white",r.strokeStyle="#ce0000",r.lineWidth=2,r.strokeText("PRESS   Z",p.width/2,250),r.fillText("PRESS   Z",p.width/2,250),r.restore());r.save();r.globalAlpha=c.ka;r.textAlign="center";r.textBaseline="center";r.font="10px silom";r.fillStyle="#00ff00";r.lineWidth=2;r.fillText("BY KCAZE (HERMAN CHAU)",p.width/2,380);r.restore()};a.R=function(a){for(var f=0;f<M.length;f++)"keypress"==M[f].L&&90==M[f].which&&
(c.blink=!1,c.ja=!1,B({object:c,J:"text_alpha",value:0,duration:1E3}).then(function(){setTimeout(function(){Fa(Ia)},1E3)}));M=[];c.blink&&(c.ja=2>Math.floor(a/500)%4?!0:!1)};a.va=function(){};return a}(),Ia=function(){function a(){return new Promise(function(a){a()})}function c(a){return a[Math.floor(Math.random()*a.length)]}function e(b,c,e){return new R({x:b,y:c,type:e,images:[f(e)],$:0,alpha:1,G:a()})}function f(a){switch(a){case v.fa:return d.images.Ca;case v.ea:return d.images.Ba}}function t(a){switch(a){case v.fa:return[d.images.Ca,
d.images.Ka,d.images.La];case v.ea:return[d.images.Ba,d.images.Ia,d.images.Ja]}}function q(){g.ga=!1;console.log("Lost :(");b.oa.clearRect(0,0,b.S.width,b.S.height);b.oa.drawImage(p,0,0);B({object:b,J:"gameover_background_alpha",value:1,duration:1E3}).then(function(){return B({object:b,J:"gameover_text_alpha",value:1,duration:1E3})}).then(function(){g.na=!0})}function u(){for(var a,b=0;b<k.D;b++){var c=g.A[b][0].I;if(c!=v.N){for(var e=!0,l=0;l<k.F;l++)if(g.A[b][l].I!=c){e=!1;break}if(e){a=b;break}}}if("undefined"!==
typeof a){c=[];for(l=0;l<k.F;l++)c.push(g.A[a][l].U);for(b=a;b<k.D-1;b++)for(l=0;l<k.F;l++)g.A[b][l]=g.A[b+1][l];for(l=0;l<k.F;l++)g.A[k.D-1][l]={I:v.N};g.ra++;var f=[];c.forEach(function(a){f.push(a.G)});var f=Promise.all(f),h=[];c.forEach(function(a){var b=f.then(function(){return B({object:a,J:"alpha",value:0,duration:100}).then(function(){a["delete"]()})});a.G=b;h.push(b)});for(b=a;b<k.D;b++)for(l=0;l<k.F;l++)(a=g.A[b][l].U)&&function(a){var b=Promise.all(h.concat([a.G]));a.G=b.then(function(){return B({object:a,
J:"y",value:a.y-k.H,ca:1})})}(a)}}function G(a,b){var c=[1,-1,0,0,1,1,-1,-1],e=[0,0,1,-1,1,-1,1,-1],l=g.A[b][a].I;if(l!=v.N)for(var h=0;8>h;h++){for(var q=c[h],u=e[h],F=!1,C=1,z=a+C*q,D=b+C*u;0<=z&&0<=D&&z<k.F&&D<k.D&&g.A[D][z].I!=v.N;){if(g.A[D][z].I==l){F=!0;break}C++;z=a+C*q;D=b+C*u}if(F)for(F=1;F<C;F++)z=a+F*q,D=b+F*u,g.A[D][z].I=l,function(a){a.images=t(a.type).concat(t(l).reverse());a.G=a.G.then(function(){return new Promise(function(b){var c;c=setInterval(function(){a.$<a.images.length-1?a.$++:
(a.type=l,a.$=0,a.images=[f(a.type)],clearInterval(c),b())},30)})})}(g.A[D][z].U)}}function Z(){for(var a=[],b=0;b<k.F;b++){var f=c(h);a.push({I:f,U:e(1+20*b,-19,f)})}for(b=0;b<k.F;b++){if(g.A[k.D-1][b].I!=v.N){q();return}for(f=k.D-1;0<f;f--)g.A[f][b]=g.A[f-1][b];g.A[0][b]=a[b]}g.A.forEach(function(a){a.forEach(function(a){var b=a.U;b&&(b.G=b.G.then(function(){return B({object:b,J:"y",value:b.y+k.H,ca:1})}))})})}function N(){for(var a=0;a<M.length;a++)"keypress"==M[a].L&&90==M[a].which&&g.na&&B({object:b,
J:"gameover_text_alpha",value:0,duration:1E3}).then(function(){Fa(Ja)});M=[]}var g,b,k={F:8,D:17,H:20,za:8,W:1E4},v={N:0,fa:1,ea:2},h=[v.fa,v.ea],H=new S;H.P=function(){b={ua:r.createPattern(d.images.background,"repeat"),K:document.createElement("canvas"),O:document.createElement("canvas"),T:document.createElement("canvas"),Aa:0,S:document.createElement("canvas"),xa:0,ya:0};b.K.width=k.F*k.H;b.K.height=(k.D+1)*k.H;b.C=b.K.getContext("2d");b.O.width=200;b.O.height=400;b.B=b.O.getContext("2d");b.S.width=
400;b.S.height=400;b.oa=b.S.getContext("2d");b.T.width=400;b.T.height=400;b.qa=b.T.getContext("2d");g={ga:!0,A:[],na:!1,ra:0,W:k.W,aa:0};g.aa=X.now()+g.W;for(var f=0;f<k.D;f++){g.A.push([]);for(var O=0;O<k.F;O++)if(2>f){var y=c(h),t=e(1+20*O,1+20*f,y);g.A[f].push({I:y,U:t})}else g.A[f].push({I:v.N})}g.ba=new R({frames:[d.images.Na,d.images.Oa,d.images.Pa,d.images.Qa],wa:[500,200,200,200],V:0,ma:X.now(),ta:function(a){a-this.ma>this.wa[this.V]&&(this.V++,this.V%=this.frames.length,this.ma=a)},x:Math.floor(k.F/
2),sa:Math.floor(k.F/2)*k.H,Fa:k.D*k.H,G:a(),M:function(a){a.drawImage(this.frames[this.V],this.sa,this.Fa)},ha:function(a){if("keypress"==a.L)switch(a.which){case 37:this.move(-1);break;case 39:this.move(1);break;case 90:this.Ea()}},move:function(b){0<=this.x+b&&this.x+b<k.F&&(this.G=this.G.then(function(){return B({object:this,J:"sprite_x",value:this.sa+b*k.H,ca:.7}).then(function(){this.x+=b;return a()}.bind(this))}.bind(this)))},next:[],Ea:function(){if(g.A[k.D-1][this.x].I!=v.N)q();else{var a=
this.next.shift();this.next.push(c(h));for(var b=k.D-1;0<b&&g.A[b-1][this.x].I==v.N;)b--;var f=e(this.x*k.H+1,(k.D-1)*k.H+1,a);g.A[b][this.x]={I:a,U:f};G(this.x,b);f.G=f.G.then(function(){d.da.Ma.play();return B({object:f,J:"y",value:1+20*b,ca:3})})}}});for(f=0;8>f;f++)g.ba.next.push(c(h))};H.M=function(a){if(Y)r.Z(),r.save(),r.globalAlpha=1,r.drawImage(b.T,0,0),r.globalAlpha=b.Aa,r.fillStyle="#000000",r.fillRect(0,0,p.width,p.height),r.restore();else if(g.ga){r.Z();b.C.clearRect(0,0,b.K.width,b.K.height);
b.B.clearRect(0,0,b.O.width,b.O.height);b.C.fillStyle="rgba(0, 0, 0, 0.5)";b.C.fillRect(0,0,b.K.width,b.K.height);b.C.save();b.C.globalAlpha=1;b.C.lineWidth=1;b.C.setLineDash([2,4]);b.C.strokeStyle="#8ed4a5";b.C.beginPath();b.C.moveTo(0,k.D*k.H-2);b.C.lineTo(k.F*k.H,k.D*k.H-2);b.C.stroke();b.C.restore();for(var c in n){var e=n[c];e.type&&(b.C.globalAlpha=e.alpha,b.C.drawImage(e.images[e.$],e.x,e.y))}b.C.globalAlpha=1;g.ba.M(b.C);b.B.fillStyle="rgba(0, 0, 0, 0.5)";b.B.fillRect(0,65,b.O.width,27);b.B.fillRect(0,
145,b.O.width,32);b.B.textAlign="center";b.B.textBaseline="center";b.B.font="32px silom";b.B.strokeStyle="#ce0000";b.B.fillStyle="#ffa100";b.B.lineWidth=4;b.B.strokeText("NEXT",100,48);b.B.fillText("NEXT",100,48);b.B.strokeText("SCORE",100,130);b.B.fillText("SCORE",100,130);b.B.textAlign="center";b.B.font="24px silom";b.B.stroke="black";c=""+g.ra;c="0".repeat(8-c.length)+c;b.B.strokeStyle="#ce0000";b.B.fillStyle="white";b.B.lineWidth=3;b.B.strokeText(c,100,170);b.B.fillText(c,100,170);for(c=0;c<k.za;c++)b.B.drawImage(f(g.ba.next[c]),
22+c*k.H,70);r.fillStyle=b.ua;r.fillRect(0,0,p.width,p.height);r.drawImage(b.K,10,20);r.drawImage(b.O,10+b.K.width+20,0);r.fillStyle="rgba(0, 0, 0, 0.5)";r.fillRect(10,8,b.K.width,5);r.fillStyle="rgba(142, 212, 165, 1)";r.fillRect(10,8,b.K.width*(g.aa-a)/g.W,5)}else r.Z(),r.save(),r.globalAlpha=1,r.drawImage(b.S,0,0),r.globalAlpha=b.xa,r.fillStyle="#290000",r.fillRect(0,0,p.width,p.height),r.globalAlpha=b.ya,r.textAlign="center",r.textBaseline="center",r.font="48px silom",r.strokeStyle="#ce0000",
r.fillStyle="#ffa100",r.lineWidth=6,r.strokeText("GAME OVER",p.width/2,p.height/2),r.fillText("GAME OVER",p.width/2,p.height/2),r.restore()};H.R=function(a){if(Y){for(a=0;a<M.length;a++)"keypress"==M[a].L&&27==M[a].which&&B({object:b,J:"pause_alpha",value:0,duration:50}).then(Ha);M=[]}else if(g.ga)a:{for(var c=0;c<M.length;c++)if("keypress"==M[c].L&&27==M[c].which){ka=X.now();Ga=performance.now();Y=!0;b.qa.clearRect(0,0,b.T.width,b.T.height);b.qa.drawImage(p,0,0);B({object:b,J:"pause_alpha",value:.75,
duration:50});M=[];break a}for(c=0;c<M.length;c++)for(var e in n)n[e].ha(M[c]);M=[];g.ba.ta(a);g.aa<a&&(Z(),g.aa=a+g.W);u()}else N()};H.va=function(){};return H}();
(function(a){var c=[];d={};c.push(la(a.images));c.push(qa(a.da));return Promise.all(c).then(function(){return d})})({images:{background:"images/background.gif",piece_blue:"images/piece_blue0.gif",piece_blue1:"images/piece_blue1.gif",piece_blue2:"images/piece_blue2.gif",piece_red:"images/piece_red0.gif",piece_red1:"images/piece_red1.gif",piece_red2:"images/piece_red2.gif",portrait_maduse:"images/gggg.gif",shooter_0:"images/shooter0.gif",shooter_1:"images/shooter1.gif",shooter_2:"images/shooter2.gif",
shooter_3:"images/shooter1.gif"},da:{sfx_shoot:jsfxr([2,0,.2540739289484918,.4,.2864944875240326,.8718781877541915,.2,-.2551874935626984,0,0,0,0,0,.23003287834580988,.15378500670194628,0,0,0,1,0,0,0,0,.5])}}).then(function(){va();Fa(Ja)});
